package.json
yarn.lock

- Update dependencies to pass expo doctor
- 

chore: update with expo doctor

---

global.ts
i18n.config.ts
src/config/navigation/index.tsx
src/contexts/walletContext/index.tsx
src/screens/promoters/SupportCauseScreen/index.tsx

- Fix some warnings
- Optimize bottom navigation
- Test A

fix: fix some warnings and i18n config

---

src/services/notifications/index.ts

- Update notification alert to console log
- Test A

fix: update notification alert to console log

---

src/components/moleculars/modals/BlankModal/styles.ts
src/components/moleculars/modals/CenteredModal/styles.ts
src/components/moleculars/modals/LoadingOverlay/styles.ts
src/screens/donations/CausesScreen/styles.ts
src/screens/donations/ChooseCauseScreen/styles.ts
src/screens/donations/DonationDoneScreen/styles.ts
src/screens/donations/ReceiveTicketScreen/styles.ts
src/screens/promoters/PaymentScreen/styles.ts
src/screens/promoters/SupportCauseScreen/CardScreen/SelectOfferSection/styles.ts
src/screens/promoters/SupportCauseScreen/CardScreen/styles.ts
src/screens/promoters/SupportCauseScreen/CommunityAddScreen/styles.ts
src/screens/promoters/SupportCauseScreen/CryptoScreen/SelectCryptoOfferSection/styles.ts
src/screens/promoters/SupportCauseScreen/CryptoScreen/styles.ts
src/screens/users/ProfileScreen/UserSection/styles.ts
src/screens/users/ProfileScreen/styles.ts
src/styles/typography/default.ts
src/styles/typography/stylized.ts

Tech 280: new typography

---

package.json
src/screens/users/ProfileScreen/ImpactCards/index.tsx
src/screens/users/ProfileScreen/NgoImpactCard/index.tsx
src/screens/users/ProfileScreen/NgoImpactCard/styles.ts
src/screens/users/ProfileScreen/NgoImpactCards/index.tsx
src/screens/users/ProfileScreen/index.tsx
src/types/entities/UserStatistics.ts
yarn.lock

Adding new user impact page

---

src/contexts/cryptoPaymentContext/index.tsx
src/contexts/networkContext/index.tsx
src/hooks/useAppState/index.tsx
src/hooks/useContract/index.ts
src/hooks/useProvider/index.ts
src/hooks/useTokenDecimals/index.tsx
src/screens/users/ProfileScreen/ImpactCards/index.tsx
src/screens/users/ProfileScreen/NgoImpactCards/index.tsx

- Update chain changed events
- Update crypto page when network changes
- Test A

refactor: update network dependecy to crypto page

---

app.json
package.json

- Updating name for Ribon native app

fix: update build number for ios

---

package.json
src/components/moleculars/LayoutHeader/index.tsx
yarn.lock

feat: add zendesk chat to our project

---

src/screens/donations/CausesScreen/index.tsx

feat: add log error to non profits stories fetch

---

src/components/moleculars/LayoutHeader/index.tsx
src/config/navigation/index.tsx
src/config/testUtils/renders.tsx
src/contexts/ticketsContext/index.test.tsx
src/contexts/ticketsContext/index.tsx
src/screens/donations/CausesScreen/index.tsx

- Add tickets context
- Fix tickets flow on causes page (starts with 0 and gains after the modal)
- Test A

feat: add Tickets context and use it on header and causes page

---

src/config/navigation/index.tsx
src/screens/donations/DonateScreen/index.tsx
src/screens/donations/DonateScreen/styles.ts
src/utils/translations/en.json
src/utils/translations/pt.json

- Change donation banner gradient do increase contrast do improve accessibility.

Fix: change donation banner gradient

---

src/screens/users/ProfileScreen/ImpactCards/index.tsx
src/screens/users/ProfileScreen/NgoImpactCard/index.tsx
src/screens/users/ProfileScreen/NgoImpactCard/styles.ts
src/screens/users/ProfileScreen/NgoImpactCards/index.tsx
src/screens/users/ProfileScreen/NgoImpactCards/styles.ts
src/screens/users/ProfileScreen/TabViewSection/index.tsx
src/screens/users/ProfileScreen/TicketDonationsTabView/index.tsx
src/screens/users/ProfileScreen/TicketDonationsTabView/styles.ts
src/screens/users/ProfileScreen/index.tsx
src/utils/translations/en.json
src/utils/translations/pt.json

- Fix scroll view warning
- Update profile page styles
- Test A

fix: remove flat list inside scroll view in ProfilePage

---

app.json
src/screens/donations/ChooseCauseScreen/CauseImage/index.tsx
src/screens/users/ProfileScreen/CommunityDonationsImpactCards/styles.ts
src/screens/users/ProfileScreen/DirectDonationsImpactCards/styles.ts
src/screens/users/ProfileScreen/NgoImpactCards/styles.ts
src/screens/users/ProfileScreen/TabViewSection/index.tsx

fix: update build numbers

---

src/components/atomics/buttons/Button/index.tsx
src/components/atomics/buttons/Button/styles.ts
src/screens/donations/CausesScreen/TicketSection/index.tsx
src/screens/donations/CausesScreen/index.tsx
src/screens/donations/DonateScreen/index.tsx
src/screens/users/ProfileScreen/ZeroDonationsSection/index.tsx

- Add Ticket Section
- Update ticket modal to show only once per donation cycle
- Update text color on Button component
- Test A

refactor: add TicketSection to CausesScreen and update text color on Btn

---

src/screens/users/ProfileScreen/DirectDonationsImpactCards/index.tsx

- Fix direct donation redirect
- Test A

feat: add param to direct donation redirect on profile

---

i18n.config.ts
src/components/moleculars/ConfigItem/index.tsx
src/components/moleculars/LayoutHeader/ChangeLanguageItem/index.tsx
src/components/moleculars/LayoutHeader/index.tsx
src/contexts/languageContext/index.tsx
src/hooks/useFormattedImpactText/index.tsx
src/screens/promoters/PaymentScreen/UserInfoSection/index.tsx
src/types/enums/Languages.ts

- General fixes from Leod's list

Geral style fixes

---

global.ts

- Update ignoreLogs patterns to ignore web3 related warnings
- Test A

fix: update ignoreLogs patterns

---

package.json
src/screens/donations/DonateScreen/index.tsx
src/utils/constants/Application.ts
yarn.lock

- Add platform param to identify when happens the donation
- eg: closes [#DAPP-689](https://ribon.atlassian.net/jira/software/c/projects/DAPP/boards/22?modal=detail&selectedIssue=DAPP-698)

[DAPP-689] Add platform param to identify when create a new donation

---

src/screens/donations/DonateScreen/index.tsx
src/utils/translations/en.json
src/utils/translations/pt.json

- add new links to terms and privacy policy
- eg: closes [#dapp-746](https://ribon.atlassian.net/jira/software/c/projects/DAPP/boards/22?modal=detail&selectedIssue=DAPP-746)

feat: add new links to terms and privacy policy

---

src/components/moleculars/CardCenterImageButton/index.tsx
src/components/moleculars/CardCenterImageButton/styles.ts
src/screens/donations/CausesScreen/styles.ts
src/utils/translations/pt.json

- Update styles of Non Profit cards
- [] New feature (non-breaking change which adds functionality)
- Test A

General fixes

---

src/contexts/cardPaymentInformationContext/index.tsx
src/lib/currentLanguage/index.tsx

- find or create a user when making a paid contribution without signing in
-  [DAPP-747](https://ribon.atlassian.net/browse/DAPP-747)

feat: Log in when making a paid contribution

---

src/contexts/networkContext/index.tsx

- Remove console logs
- Test A

fix: remove console logs

---

package.json
src/screens/donations/CausesScreen/index.tsx
src/screens/donations/CausesScreen/styles.ts
src/utils/translations/en.json
src/utils/translations/pt.json
yarn.lock

- Show only non profits and causes with pool balance on causesPage
- Added a emptyCard in case of no causes
- Create a pool balance with balance 0 and see the home page changing

Tech 479: Show only non profits with pool balance

---

src/screens/content/ForYouScreen/TabViewSection/index.tsx
src/screens/content/ForYouScreen/index.tsx

- Locked page just in news tab
- eg: closes [#DAPP-730](https://ribon.atlassian.net/jira/software/c/projects/DAPP/boards/22?modal=detail&selectedIssue=DAPP-730)

[DAPP-730] Locked page in news tab

---

src/screens/content/ForYouScreen/TasksSection/index.tsx
src/screens/content/ForYouScreen/TasksSection/styles.ts

- Show next step of integration when has no ticket in task page
- eg: closes [#DAPP-724]()

[DAPP-724] Next step to integration

---

package.json
src/components/moleculars/CardImageText/index.tsx
src/components/moleculars/CardImageText/styles.ts
src/screens/users/ProfileScreen/NgoImpactCard/index.tsx
src/screens/users/ProfileScreen/NgoImpactCards/index.tsx
src/utils/translations/en.json
src/utils/translations/pt.json
yarn.lock

- Add legacy impact to profile page
- Test A

feat: add Legacy impact to profile page

---

src/components/moleculars/notifications/InlineNotification/index.tsx

- Update InlineNotification styles
- Test A

style: update icon color by type in InlineNotification

---

App.tsx
src/config/navigation/index.tsx
src/contexts/tasksContext/index.tsx
src/hooks/useFormattedImpactText/index.tsx
src/lib/Toast/index.tsx
src/lib/dateUtils/index.ts
src/screens/content/ForYouScreen/TabViewSection/index.tsx
src/screens/content/ForYouScreen/TasksSection/index.tsx
src/utils/constants/Tasks.ts
src/utils/translations/en.json
src/utils/translations/pt.json

- Add toast of celebration when finish all tasks
- eg: closes [#DAPP-718](https://ribon.atlassian.net/jira/software/c/projects/DAPP/boards/22?modal=detail&selectedIssue=DAPP-718)

[DAPP-718] Toast of celebration when finish all tasks

---

src/screens/donations/DonationDoneStack/ChooseCauseScreen/CauseImage/styles.ts
src/screens/donations/DonationDoneStack/ChooseCauseScreen/index.tsx
src/screens/donations/DonationDoneStack/ChooseCauseScreen/styles.ts

- Adjust layout of donation done page
- eg: closes [#DAPP-757]()

[DAPP-757] Adjust layout of donation done page

---

app.config.js

Version update to 5.0.0

---

src/screens/content/ForYouScreen/NewsSection/index.tsx
src/screens/users/ProfileScreen/ImpactCards/index.tsx
src/screens/users/ProfileScreen/ImpactMigrationNotification/styles.ts
src/screens/users/ProfileScreen/index.tsx
src/utils/constants/Tasks.ts

- show the onboarding post 3 times
- Test A

feat: show the onboarding post 3 times

---

.github/workflows/automerge-labeler.yml
yarn.lock

- Add automerge labeler workflow

feat: add automerge labeler workflow

---

package.json
src/hooks/useFormattedImpactText/index.tsx
src/screens/content/ForYouScreen/TasksSection/index.tsx
src/screens/users/ProfileScreen/CommunityDonationsImpactCards/index.tsx
src/utils/translations/en.json
src/utils/translations/pt.json
yarn.lock

- Add legacy contributions cards to impact page
- Test A

feat: add legacy contributions to CommunityDonationsImpactCards

---

src/contexts/languageContext/index.tsx
src/services/analytics/index.ts

- adds language to user property on firebase
- Closes [DAPP-811](https://ribon.atlassian.net/browse/DAPP-811)
- Test A

feat: dapp-811

---

src/screens/content/ForYouScreen/TabViewSection/index.tsx
src/screens/content/ForYouScreen/TasksSection/index.tsx
src/screens/content/ForYouScreen/index.tsx
src/screens/donations/DonationDoneStack/AvailableArticleScreen/index.tsx
src/types/index.tsx

fix: available article redirects 

---

src/screens/promoters/PaymentScreen/index.tsx

fix: button colors while paying

---

src/components/moleculars/layouts/ArticleLayout/index.tsx
src/screens/content/ForYouScreen/LockedSection/index.tsx
src/screens/content/ForYouScreen/NewsSection/index.tsx
src/screens/donations/DonationDoneStack/AvailableArticleScreen/index.tsx

- Add events to posts news from for you screen
- eg: closes [#DAPP-816](https://ribon.atlassian.net/jira/software/c/projects/DAPP/boards/22?modal=detail&selectedIssue=DAPP-816)

feat: add events to posts and for you screen

---

app.config.js

feat: adjust version of build

---

src/screens/promoters/SupportCauseScreen/CardScreen/index.tsx
src/screens/promoters/SupportCauseScreen/CryptoScreen/index.tsx

-  Preserve cause when changing currency at payment screen 
- closes [DAPP-710](https://ribon.atlassian.net/browse/DAPP-710)

fix: dapp-710 

---

src/utils/translations/pt.json

- Update copy on impact migration message
- Go to profile page and check the new copy in pt-br

fix: update copy to impact migration

---

app.config.js

feat: adjust version

---

src/components/moleculars/LayoutHeader/index.tsx

Remove login button when the user is not logged

fix: remove login button when the user is not logged

---

src/screens/donations/DonationDoneStack/DonationDoneScreen/index.tsx
src/screens/promoters/ContributionDoneScreen/index.tsx
src/screens/promoters/PaymentScreen/index.tsx
src/screens/templates/DoneScreenTemplate/index.tsx

refactor: ngo and cause new images

---

src/screens/users/ProfileScreen/ImpactMigrationNotification/index.tsx
src/utils/translations/en.json
src/utils/translations/pt.json

- Change migration notification copy
- Test A

Tech 529: Change migration notification copy

---

.gitignore
app.config.js

- Update build number
- Test A

build: update build number and app version

---

app.config.js
src/screens/donations/DonateScreen/EmailInputSection/index.tsx
src/screens/donations/DonateScreen/SignedInSection/index.tsx

build: update app version

---

App.tsx
package.json
src/config/DebugEventsView/DebugView/index.tsx
src/config/DebugEventsView/DebugView/styles.ts
src/config/DebugEventsView/helpers.ts
src/config/DebugEventsView/index.tsx
src/config/DebugEventsView/styles.ts
src/services/analytics/index.ts

https://github.com/RibonDAO/app/assets/27820474/a09ef9cd-d540-4cdb-a9a9-c83e5d914df3
- Add debug view
run the server with `yarn start-debug -c` and check the events being logged

feat: add debug view

---

package.json
src/contexts/cardPaymentInformationContext/index.tsx
src/contexts/cryptoPaymentContext/index.tsx
src/screens/promoters/SupportCauseScreen/CardScreen/index.tsx
src/screens/promoters/SupportNonProfitScreen/CardScreen/index.tsx
src/types/index.tsx
yarn.lock

- add platform to redirect to payments

feat: add platform to payments

---

.github/workflows/promote-develop-main-pr.yml

directs flow to staging instead of develop

fix: directs flow to staging instead of develop

---

src/services/deepLink/index.ts

- remove $ from integration_id param
- Test A

Prod3-74: remove $ from integration_id param

---

app.config.js

feat: build

---

src/components/moleculars/LayoutHeader/index.tsx
src/components/moleculars/UserSupportSection/index.tsx

fix: fixes event name

---

src/contexts/cardPaymentInformationContext/index.tsx
src/screens/promoters/CheckoutScreen/CardSection/index.tsx
src/screens/promoters/CheckoutScreen/Components/CreditCardForm/index.tsx
src/screens/promoters/CheckoutScreen/Components/Header/styles.ts
src/screens/promoters/CheckoutScreen/index.tsx
src/screens/promoters/CheckoutScreen/placeholder.tsx
src/screens/promoters/SupportCauseScreen/CardScreen/SelectOfferSection/index.tsx
src/screens/promoters/SupportCauseScreen/CardScreen/index.tsx
src/screens/promoters/SupportNonProfitScreen/CardScreen/index.tsx

- Add events to new form
- Add redirect to new form
- Test A

feat: add events to new form and redirect to it

---

app.config.js

feat: add version

---

app.config.js
package.json
src/config/navigation/index.tsx
src/contexts/cardPaymentInformationContext/index.tsx
src/screens/content/ForYouScreen/TabViewSection/index.tsx
src/screens/content/ForYouScreen/index.tsx
src/screens/donations/CausesScreen/index.tsx
src/screens/donations/DonateScreen/EmailInputSection/index.tsx
src/screens/donations/DonateScreen/SignedInSection/index.tsx
src/screens/promoters/CheckoutScreen/Components/ApplePaySection/index.tsx
src/screens/promoters/CheckoutScreen/Components/GooglePaySection/index.tsx
yarn.lock

- Use integrationContext to use integrationId from deeplink 
- eg: closes [#PROD3-105]()

feat: remove constant to use integration id from context

---

src/screens/donations/DonationDoneStack/PostDonationScreen/ContributionImage/index.tsx

- set cause index on post donation page
- Test A

PROD 151: set cause index on post donation page

---

src/screens/promoters/CheckoutScreen/CardSection/index.tsx
src/screens/promoters/CheckoutScreen/Components/CreditCardForm/index.tsx
src/screens/promoters/CheckoutScreen/Components/GooglePaySection/index.tsx

- Add tax id to google pay section if gateway is stripe
- Test A

fix: add tax id to google pay section if gateway is stripe

---

src/screens/donations/CausesScreen/index.tsx

fix: adjust filter of causes on causes screen

---

app.config.js

fix: number of build

---

src/contexts/checkoutContext/index.tsx
src/screens/promoters/CheckoutScreen/CardSection/index.tsx
src/screens/promoters/CheckoutScreen/Components/ApplePaySection/index.tsx
src/screens/promoters/CheckoutScreen/Components/GooglePaySection/index.tsx
src/screens/promoters/CheckoutScreen/Components/PriceSelection/index.tsx
src/screens/promoters/CheckoutScreen/index.tsx
src/screens/promoters/RecurrenceScreen/index.tsx
src/utils/translations/en.json
src/utils/translations/pt.json

- wait for offer to show card sections
- change offer to offerPrice on checkoutContext
- Test A

fix: google pay section without offer

---

app.config.js
src/screens/promoters/CheckoutScreen/Components/ApplePaySection/index.tsx
src/screens/promoters/CheckoutScreen/Components/GooglePaySection/index.tsx
src/utils/translations/en.json
src/utils/translations/pt.json

- added login and error toast on gPay and applePay
- Test A

fix: added login and error toast on gPay and applePay

---

src/screens/promoters/CheckoutScreen/CardSection/index.tsx

- set the current offer when the offer with the chosen price does not exist
- Test A

fix: setCurrentOffer 

---

src/screens/promoters/CheckoutScreen/CardSection/index.tsx
src/screens/promoters/RecurrenceScreen/index.tsx
src/utils/translations/en.json
src/utils/translations/pt.json

fix: recurrence title

---

app.config.js

- update build version
- Test A

fix: update build version

---

src/screens/donations/CausesScreen/index.tsx
src/screens/promoters/SupportCauseScreen/CardScreen/index.tsx
src/screens/promoters/SupportCauseScreen/CryptoScreen/index.tsx
src/screens/promoters/SupportNonProfitScreen/CardScreen/index.tsx

- Makes event parameters send a string with the current order of causes and non profits to make it easily accessible on mixpanel

refactor: adjusts event parameters

---

app.config.js

chore: att num of build and version

---

package.json
src/lib/formatters/dateFormatter/index.test.ts
src/lib/formatters/dateFormatter/index.ts
src/screens/promoters/MonthlyContributionsScreen/index.tsx
yarn.lock

- added subscription next payment attempt
- Test A

feat: subscription next payment attempt

---

src/hooks/useImpactConversion/index.tsx
src/screens/donations/DonationDoneStack/PostDonationScreen/ContributionImage/index.tsx
src/screens/donations/DonationDoneStack/PostDonationScreen/ContributionImage/styles.ts
src/screens/donations/DonationDoneStack/PostDonationScreen/index.tsx
src/utils/translations/en.json
src/utils/translations/pt.json

- Adjust copy of cta in post donation
- Adjust redirect to checkout payment
- eg: closes [#PROD3-121](https://ribon.atlassian.net/jira/software/c/projects/PROD3/boards/28?modal=detail&selectedIssue=PROD3-121)
- Test A

[PROD3-121] Adjust cta buttons on post donation screen

---

src/screens/content/ForYouScreen/TasksSection/MonthlyTasksSection/index.tsx
src/screens/donations/CausesScreen/ContributionSection/ContributionCard/index.tsx
src/screens/donations/CausesScreen/ContributionSection/ContributionCard/styles.ts
src/screens/donations/CausesScreen/ContributionSection/index.tsx
src/screens/donations/CausesScreen/ContributionSection/styles.ts
src/screens/donations/CausesScreen/index.tsx
src/utils/translations/en.json
src/utils/translations/pt.json

- Show cta after donation
- Show cta in super tasks
- eg: closes [#PROD3-125]()

[PROD3-125] Add CTA on CausesScreen and Super Tasks

---

src/screens/donations/DonateScreen/EmailInputSection/index.tsx

- external id on email input section
- Test A

fix: external id on email input section

---

src/screens/donations/CausesScreen/ContributionSection/ContributionCard/index.tsx
src/screens/donations/CausesScreen/index.tsx
src/utils/translations/en.json
src/utils/translations/pt.json

fix: show contribution just when has current user and contribution

---

src/components/moleculars/LayoutHeader/index.tsx
src/components/moleculars/UserSupportBanner/index.tsx
src/components/moleculars/UserSupportSection/index.tsx

fix: email

---

src/screens/donations/CausesScreen/ContributionSection/ContributionCard/index.tsx
src/screens/donations/DonationDoneStack/PostDonationScreen/ContributionImage/index.tsx
src/screens/promoters/SupportCauseScreen/CardScreen/index.tsx
src/screens/promoters/SupportNonProfitScreen/CardScreen/index.tsx
src/utils/translations/en.json
src/utils/translations/pt.json

- Adjust translate
- Add language to send to web page
- Test A

fix: redirect and translate

---

package.json
src/screens/content/ForYouScreen/NewsSection/index.tsx
yarn.lock

- updates news/articles request for only getting the ones after the user was created

fix: update news/articles request

---

app.config.js

feat: add new version and builder number

---

src/components/atomics/buttons/Button/index.tsx
src/components/moleculars/CardCenterImageButton/index.tsx
src/components/moleculars/CardCenterImageButton/styles.ts
src/screens/donations/CausesScreen/index.tsx

- changes cause/non profit name layout on non profit card so it fits better with bigger names
- [#prod3-199](https://ribon.atlassian.net/browse/PROD3-199?atlOrigin=eyJpIjoiOWM3OWUyZTRjYWMwNDI5MDg3NDEyOTUwMjNlNGZjNDMiLCJwIjoiaiJ9)

chore: change cause/non pft title layout causes pg

---

src/components/moleculars/BannerInfo/styles.ts
src/components/moleculars/CardCenterImageButton/index.tsx
src/hooks/useImpactConversion/index.tsx
src/screens/users/ImpactScreen/CommunityDonationsImpactCards/index.tsx
src/screens/users/ImpactScreen/DirectDonationsImpactCards/index.tsx
src/utils/translations/en.json

- fix impact description and banner layout
- Verify the banner about integration in causes page when has a integration 
- Verify impact description from cta

fix impact description and banner layout

---

app.config.js

feat: add version number

---

src/screens/donations/CausesScreen/ContributionSection/ContributionCard/index.tsx

- Contribution cta event name
- Test A

fix: Contribution cta event name

---

package.json
src/components/atomics/RoundButton/index.tsx
src/screens/donations/CausesScreen/index.tsx
src/screens/promoters/SupportCauseScreen/CardScreen/SelectOfferSection/index.test.tsx
src/screens/promoters/SupportNonProfitScreen/index.test.tsx
yarn.lock

- changes cause status from bool to enum
- run yarn
- [#prod3-180](https://ribon.atlassian.net/browse/PROD3-180?atlOrigin=eyJpIjoiZWUxNGFlNTAwMTUwNDc3NDg0ZmQzMzMxY2Q4MzdkMWIiLCJwIjoiaiJ9)

fix: updates status type on cause

---

src/screens/users/ContributionStatsScreen/VideoSection/index.tsx

- adds English community impact video
- closes [PROD3-149](https://ribon.atlassian.net/browse/PROD3-149)
- Test A

fix: prod3-149

---

app.config.js
src/services/crm/index.ts
src/utils/constants/Application.ts

fix: crm to env keys

---

src/components/moleculars/layouts/ArticleLayout/index.tsx

fix: remove event

---

src/hooks/useImpactConversion/index.tsx

- Changes the contribution card offer
- [X ] Chore (change that does not effect how the code works, eg: change color)
- Test A

change offer

---

app.config.js

fix: update version

---

src/utils/translations/en.json

- support translation
- Test A

fix: support translation

---

src/screens/donations/DonateScreen/EmailInputSection/index.tsx

- source was only being created on checkout part
- Test A

fix: createSource on first donation

---

src/screens/donations/DonateScreen/index.tsx
src/utils/translations/en.json
src/utils/translations/pt.json

Fixes animation that was getting stuck previously

fix: fixes animation

---

app.config.js
src/screens/promoters/SupportCauseScreen/CardScreen/index.tsx

feat: add new version number

---

app.config.js

fix: version

---

App.tsx

Fix status bar white-on-white when device is in dark mode. Both android and ios

fix: status bar in dark mode is white-on-white

---

src/screens/content/ForYouScreen/TasksSection/DailyTasksSection/index.tsx
src/utils/constants/Tasks.ts
src/utils/translations/en.json
src/utils/translations/pt.json

feat: giving day task

---

src/utils/constants/Tasks.ts

chore: remove giving day stuff

---

src/screens/donations/CausesScreen/ContributionSection/ContributionCard/index.tsx
src/screens/donations/DonationDoneStack/PostDonationScreen/ContributionImage/index.tsx
src/screens/promoters/CheckoutScreen/CardSection/index.tsx
src/screens/promoters/SupportCauseScreen/CardScreen/index.tsx
src/screens/promoters/SupportNonProfitScreen/CardScreen/index.tsx
yarn.lock

Enable apple pay
NOTE: It MUST be tested in internal beta before push to production.

feat: enable apple pay

---

app.config.js
src/screens/promoters/CheckoutScreen/Components/ModalButtonSelector/index.tsx
src/screens/promoters/CheckoutScreen/Components/ModalButtonSelector/styles.ts

fix: remove prop

---

src/components/moleculars/CardCampaign/index.tsx
src/screens/donations/CausesScreen/ContributionSection/index.tsx
src/utils/translations/en.json
src/utils/translations/pt.json

feat: default impression card data

---

app.config.js

fix: number of version and build

---

app.config.js
package.json
src/components/moleculars/CardCampaign/index.tsx
src/screens/donations/CausesScreen/TicketSection/index.tsx
src/screens/donations/auth/InsertEmailAccountScreen/index.tsx
src/screens/promoters/CheckoutScreen/CardSection/index.tsx
src/screens/promoters/CheckoutScreen/Components/GooglePaySection/index.tsx
src/screens/users/ImpactScreen/ProfileSection/index.tsx
yarn.lock

fix: is platform pay supported

---

app.config.js

fix: number of version

---

app.config.js
src/screens/promoters/CheckoutScreen/CardSection/index.tsx

- hide google pay for android versions <= 10
- Test A

fix: hide google pay for android versions <= 10

---

src/screens/auth/SignInExtraTicketScreen/index.test.tsx
src/utils/translations/en.json
src/utils/translations/pt.json

Fix: copy on sign in page

---

src/screens/promoters/CheckoutScreen/CardSection/index.tsx
src/screens/promoters/CheckoutScreen/CardSection/styles.ts
src/screens/promoters/CheckoutScreen/Components/TrustSeal/styles.ts
src/utils/translations/en.json
src/utils/translations/pt.json

- Add info about monthly contribution on checkout screen
- Verify if on checkout screen in monthly contribution shows that info

feat: add info about monthly contribution

---

src/screens/promoters/CheckoutScreen/CardSection/index.tsx
src/screens/promoters/CheckoutScreen/Components/ApplePaySection/index.tsx
src/screens/promoters/CheckoutScreen/Components/CreditCardForm/index.tsx
src/screens/promoters/CheckoutScreen/Components/GooglePaySection/index.tsx
src/screens/promoters/CheckoutScreen/Components/PixSection/index.tsx

- when country is brazil shows cpf 
- eg: closes [#PROD3-388](https://ribon.atlassian.net/jira/software/c/projects/PROD3/boards/28/backlog?selectedIssue=PROD3-388)

fix: adjust input of tax id to shows cpf when is br country

---

app.config.js
src/screens/promoters/CheckoutScreen/CardSection/index.tsx

- enable google pay for android 10
- Test A

Fix: enable google pay for android 10

---

package.json
src/services/authenticationApi/index.ts
yarn.lock

- call request new token inside initialize function
- shared updated to do the same
- we had to duplicate the code, because on shared we use cookies and on app we need to use local Storage
- if you continue authenticated on app after 2 hours
- or you can test with local backend and change expiry function to 2.minutes

fix: request new token inside initialize function

---

src/screens/donations/CausesScreen/index.tsx
src/screens/promoters/SupportCauseScreen/CardScreen/index.tsx
src/screens/promoters/SupportCauseScreen/CryptoScreen/index.tsx
src/screens/promoters/SupportNonProfitScreen/CardScreen/index.tsx

- remove order events 🎉
- Test A

fix: remove order events

---

src/hooks/useCachedResources.ts
src/services/api/index.ts
src/services/authenticationApi/index.ts

- Sends platform on headers
- [#prod3-433](https://ribon.atlassian.net/browse/PROD3-433?atlOrigin=eyJpIjoiYjQ2M2M4MzA4YTE5NDI2Mzk4YzllZDkwMDM1NWE1MmQiLCJwIjoiaiJ9)
- try to authenticate/refresh token and see the platform changing

feat: sends platform on headers

---

app.config.js
src/hooks/useDonationFlow/index.ts
src/hooks/useTickets/index.ts
src/screens/donations/auth/DonationSignInScreen/index.tsx
src/screens/donations/auth/InsertEmailAccountScreen/index.tsx
src/screens/donations/auth/SignedInScreen/index.tsx

- externalId split and onDonationSuccess
- Test A

Fix: externalId split and onDonationSuccess

---

src/contexts/cardPaymentInformationContext/index.tsx
src/contexts/pixInformationContext/index.tsx
src/screens/promoters/CheckoutScreen/Components/ApplePaySection/index.tsx
src/screens/promoters/CheckoutScreen/Components/GooglePaySection/index.tsx

fix: event name from cause to nonprofit

---

app.config.js
src/config/navigation/LinkingConfiguration.ts
src/config/testUtils/test-helper.tsx
src/screens/content/ForYouScreen/index.tsx
src/screens/donations/DonationDoneStack/DonationDoneScreen/index.tsx

- impact on donation done screen
- donation done page to donation done screen
- refetchTickets on for you screen
- Test A

fix: impact on donation done screen

---

src/components/moleculars/CardCampaign/index.tsx

- Add event to card campaign 
- https://ribon.atlassian.net/jira/software/c/projects/PROD3/boards/28?selectedIssue=PROD3-432

fix: event on card campaing

---

app.config.js

fix: app version

---

app.config.js
package.json
src/hooks/useTickets/index.ts
src/screens/donations/ReceiveTicketScreen/index.tsx
yarn.lock

- collect by integration parameters order
- Test A

fix: collect by integration

---

src/components/moleculars/PaymentMethods/ApplePaySection/index.tsx
src/components/moleculars/PaymentMethods/GooglePaySection/index.tsx
src/contexts/cardPaymentInformationContext/index.tsx
src/contexts/pixInformationContext/index.tsx
src/screens/promoters/ClubScreen/index.tsx
src/screens/promoters/club/CheckoutScreen/PaymentMethodSection/index.tsx

- added correct navigation flow
- Test A

feat: added correct navigation flow

---

src/services/deepLink/index.ts

Add an internal first open event

feat: add first open event when app opens with deep link

---

src/contexts/pixInformationContext/index.tsx
src/screens/donations/CausesScreen/index.tsx
src/screens/donations/CausesScreen/styles.ts
src/screens/promoters/ClubScreen/components/PurchaseSection/index.tsx
src/screens/promoters/club/CheckoutScreen/PaymentMethodSection/index.tsx

- banner(cta club) and bug fix
- Test A

feat: banner(cta club) and bug fix

---

src/screens/donations/CausesScreen/errorModalSection/index.tsx
src/utils/translations/en.json
src/utils/translations/pt.json

- error modal to success
- Test A

prod 464: error modal to success

---

app.config.js
src/utils/translations/en.json
src/utils/translations/pt.json

feat: test eas update

---

App.tsx
app.config.js
package.json
src/services/appsFlyer/index.ts
src/utils/constants/Application.ts
yarn.lock

AppsFlyer is our new Mobile Measurement Partner!
- We need to setup appsflyer as our MMP to track apple things like signup events.

feat: appsflyer sdk setup

---

package.json
src/components/moleculars/buttons/AppleLogin/index.tsx
src/components/moleculars/buttons/GoogleLogin/index.tsx
src/screens/donations/CausesScreen/ClubSection/index.tsx
src/screens/donations/CausesScreen/ClubSection/styles.ts
src/screens/donations/CausesScreen/index.tsx
src/screens/donations/CausesScreen/styles.ts
src/utils/constants/Application.ts
yarn.lock

prod 360: club banner

---

src/components/moleculars/buttons/AppleLogin/index.tsx
src/components/moleculars/buttons/GoogleLogin/index.tsx
src/hooks/useTickets/index.ts
src/screens/donations/CausesScreen/index.tsx
src/screens/donations/auth/DonationSignInScreen/index.tsx
src/screens/donations/auth/InsertEmailAccountScreen/index.tsx
src/screens/donations/auth/SignedInScreen/index.tsx

- ticketCollected event
- Test A

Prod 477: ticketCollected event

---

app.config.js
src/services/appsFlyer/index.ts
src/utils/constants/Application.ts

fix: use expo secrets to handle appsflyer env vars

---

src/components/moleculars/LayoutHeader/TicketSection/index.tsx

- zero tickets redirect
- Test A

fix: zero tickets redirect

---

src/components/moleculars/buttons/AppleLogin/index.tsx
src/components/moleculars/buttons/GoogleLogin/index.tsx

- remove loading overlay from apple and google login 
- Test A

fix: remove loading overlay

---

src/screens/promoters/PixInstructionsScreen/index.tsx
src/utils/translations/en.json
src/utils/translations/pt.json

- Adjust pix instruction payable name to "Payment Of Ribon Club" when target is club
- eg: closes [#PROD3-483]()

[PROD3-483] Adjust pix instruction

---

src/screens/promoters/ClubScreen/components/BenefitsSection/index.tsx
src/screens/promoters/ClubScreen/components/BenefitsSection/styles.ts
src/screens/promoters/ClubScreen/components/DepoimentsSection/styles.ts
src/screens/promoters/ClubScreen/styles.ts

prod 484: club screen layout

---

src/screens/promoters/SubscriptionsScreen/CancelSubscriptionModal/index.tsx
src/screens/promoters/SubscriptionsScreen/index.tsx

- Adds manage subscriptions events 
- closes [PROD3-496](https://ribon.atlassian.net/browse/PROD3-496)

feat: adds manage subscription events

---

app.config.js
src/screens/promoters/SubscriptionsScreen/CancelSubscriptionModal/index.tsx

- Added loading to avoid send more than one email
- Test A

fix: cancel subscription email

---

src/screens/users/ImpactScreen/ImpactCards/index.tsx

-  total donated dynamic by language
- Test A

fix: total donated dynamic

---

src/screens/donations/SelectTicketsScreen/index.tsx
src/screens/donations/auth/DonationSignInScreen/index.tsx
src/screens/donations/auth/InsertEmailAccountScreen/index.tsx
src/screens/donations/auth/SignedInScreen/index.tsx

-  ticketDonated_end event
- Test A

rpdo3 58: ticketDonated_end event

---

app.config.js

feat: app version

---

src/components/moleculars/Card/index.tsx
src/components/moleculars/CardInfo/index.tsx
src/components/moleculars/CardInfo/styles.ts

- cardInfo component
- to test on causesScreen:
```
<CardInfo
icon={{
name: "volunteer_activism",
type: "rounded",
color: theme.colors.brand.primary[800],
size: 20,
}}
title="Como ganho mais tickets?"
titleColor={theme.colors.neutral[800]}
iconBackgroundColor={theme.colors.brand.primary[100]}
backgroundColor={theme.colors.brand.secondary[25]}
>
Dinheiro de verdade, mas que vale exclusivamente para doações para
projetos sociais dentro da Ribon
</CardInfo>
```

prod 513: cardInfo

---

src/components/moleculars/PaymentMethods/PixSection/index.tsx
src/screens/promoters/ClubScreen/Header/styles.ts
src/screens/promoters/ClubScreen/components/DepoimentsSection/styles.ts
src/screens/promoters/ClubScreen/index.tsx
src/screens/users/ImpactScreen/TabViewSection/index.tsx
src/screens/users/ImpactScreen/index.tsx
src/screens/users/ImpactScreen/styles.ts
src/utils/translations/en.json
src/utils/translations/pt.json

- fix layout problems
- Test A

fix: layout

---

package.json
src/components/moleculars/PaymentMethods/ApplePaySection/index.tsx
src/components/moleculars/PaymentMethods/CreditCardSection/index.tsx
src/components/moleculars/PaymentMethods/CreditCardSection/styles.ts
src/components/moleculars/PaymentMethods/GooglePaySection/index.tsx
src/components/moleculars/PaymentMethods/PixSection/index.tsx
src/components/moleculars/PaymentMethods/PixSection/styles.ts
src/components/moleculars/SliderButton/index.test.tsx
src/components/moleculars/SliderButton/index.tsx
src/config/testUtils/setupTests.ts
src/contexts/cardPaymentInformationContext/index.tsx
src/contexts/pixInformationContext/index.tsx
src/screens/donations/SelectTicketsScreen/index.tsx
yarn.lock

- slider button for minimumNumberOfTickets
- lint
- layout
- Test A

prod 491: slider button for minimumNumberOfTickets

---

src/screens/donations/SelectTicketsScreen/index.tsx

-  just in case lastImpact is null
- Test A

fix: just in case lastImpact is null

---

src/utils/translations/en.json
src/utils/translations/pt.json

fix: adjust arrow

---

package.json
src/components/moleculars/CardReport/index.test.tsx
src/components/moleculars/CardReport/index.tsx
src/components/moleculars/CardReport/styles.ts
src/screens/donations/CausesScreen/ReportsSection/index.tsx
src/screens/donations/CausesScreen/ReportsSection/styles.ts
src/screens/donations/CausesScreen/index.tsx
src/screens/donations/CausesScreen/styles.ts
src/utils/translations/en.json
src/utils/translations/pt.json
yarn.lock

- Create the reports section and the components that will display and link with the reports.
- Create reports in the manager and add a report with name "see all" to the component.
- If no reports, the reports component do not show.

Feature/reports [PROD3 - 510]

---

src/services/appsFlyer/index.ts

Remove app id to permit both android and ios apps associated to dev key

fix: multi-app appsflyer install

---

src/screens/onboarding/v2/FirstSection/index.tsx

Prod3 520: events

---

src/components/moleculars/CardReport/index.tsx
src/screens/promoters/ClubScreen/index.tsx

chore: open reports page in webview instead of external browser

---

src/config/navigation/index.tsx
src/utils/translations/en.json
src/utils/translations/pt.json

- Tickets to donate tickets
- Impact to My Impact
- eg: closes [#PROD3-511]()

[PROD3-511] Adjust navbar copy

---

src/screens/content/EarnTicketsScreen/TasksSection/index.tsx
src/screens/donations/SelectTicketsScreen/index.tsx
src/screens/donations/auth/DonationSignInScreen/index.tsx
src/screens/donations/auth/InsertEmailAccountScreen/index.tsx
src/screens/donations/auth/SignedInScreen/index.tsx
src/screens/promoters/CheckoutScreen/CardSection/styles.ts
src/screens/promoters/SupportCauseScreen/CardScreen/index.tsx
src/screens/promoters/SupportCauseScreen/CardScreen/styles.ts
src/screens/promoters/SupportCauseScreen/CryptoScreen/index.tsx
src/screens/promoters/SupportCauseScreen/CryptoScreen/styles.ts
src/screens/promoters/SupportNonProfitScreen/index.tsx
src/screens/promoters/SupportNonProfitScreen/styles.ts

- Fix completed task when donate ticket
- Arrows to navigate back 
- Donate all tasks and click to make a contribution on task in super tasks

fix: completed task when donate ticket

---

src/screens/onboarding/v2/FirstSection/index.tsx

fix: onboarding title

---

app.config.js
src/components/moleculars/BannerInfo/styles.ts
src/components/moleculars/IntegrationBanner/index.tsx
src/components/moleculars/NewHeader/TicketSection/index.tsx
src/components/moleculars/NewHeader/styles.ts
src/screens/donations/CausesScreen/ContributionSection/index.tsx
src/screens/donations/CausesScreen/ContributionSection/styles.ts
src/screens/donations/CausesScreen/index.tsx
src/screens/donations/CausesScreen/styles.ts
src/screens/promoters/SubscriptionsScreen/CancelSubscriptionModal/index.tsx
src/utils/translations/en.json
src/utils/translations/pt.json

- Adjust copy's and layouts related after internal testing https://www.figma.com/file/v018rp6GrSiwUYmdFy4KPA/Entendimento-e-valoriza%C3%A7%C3%A3o-do-Ticket-(informacional)?type=design&node-id=2275-787&mode=design&t=Kb5dU8yGxuweXp3F-0

fix: copys and layout adjusts

---

src/screens/donations/SelectTicketsScreen/index.tsx

- Fixes impact computation for non profits with impact_by_ticket equal to zero

fix: impact calculus for np w/ no impact by ticket

---

app.config.js
src/screens/donations/CausesScreen/ContributionSection/index.tsx
src/screens/donations/CausesScreen/ContributionSection/styles.ts
src/screens/donations/CausesScreen/index.tsx
src/screens/donations/CausesScreen/styles.ts
src/utils/translations/en.json
src/utils/translations/pt.json

- Adjust campaign card position and margin https://www.figma.com/file/v018rp6GrSiwUYmdFy4KPA/Entendimento-e-valoriza%C3%A7%C3%A3o-do-Ticket-(informacional)?type=design&node-id=2362-60&mode=design&t=uRwcErzW7eduBjT1-0
- Test A

fix: campaign card position

---

.github/pull_request_template.md

- adds styled components check on PR template 

chore: adds styled components check

---

package.json
yarn.lock

Provides a `<Markdown/>` component that translates a markdown string to native code, allowing styles and more.
Usage:

feat: add react markdown display

---

src/components/moleculars/NewHeader/TicketSection/index.tsx
src/components/moleculars/NewHeader/styles.ts

https://github.com/RibonDAO/app/assets/24739860/7b4b1bf1-04e6-4999-9648-109a5ba8de3c

feat: animated ticket section

---

package.json
src/components/atomics/buttons/ArrowBackButton/index.tsx
src/components/atomics/buttons/ArrowBackButton/styles.ts
src/components/atomics/buttons/ButtonSwitch/index.tsx
src/config/navigation/index.tsx
src/screens/auth/SentMagicLinkEmailScreen/index.tsx
yarn.lock

- Change copy of SentMagicLinkScreen
- Header back button
- Color of switch in android
- eg: closes [#PROD3-546]()
- Test sign in in magic link
- Test screen with back button in ios and android
- Test switch color on android and ios

[PROD3-546] Change copy of SentMagicLinkScreen

---

src/screens/donations/HomeScreen/index.tsx

- navigate on HomeScreen
- Test A

fix: navigate on HomeScreen

---

package.json
src/components/moleculars/OngCard/index.tsx
src/components/moleculars/OngCard/styles.ts
yarn.lock

fix: ong card

---

src/components/moleculars/NewHeader/TicketSection/index.tsx

Remove counter animation from causes screen header. 
We'll add it again soon.
https://github.com/RibonDAO/app/assets/24739860/3dbedf8a-7b50-41aa-8997-ffde26d461db

feat: remove counter animation for now

---

app.config.js
package.json
yarn.lock

- update sentry version based on npx expo-doctor@latest
- Test A

fix: sentry version

---

app.config.js
src/hooks/useCachedResources.ts
src/screens/coupons/GiveTicketByCouponScreen/index.tsx
src/screens/donations/CausesScreen/index.tsx
src/screens/donations/HomeScreen/index.tsx

- Added splash screen on home
- hide splash screen only on home
- fix navigation to causesScreen
- Test A

fix: splash screen

---

src/hooks/useCoupons/index.ts

- handleCanCollectByCouponId
- Test A

fix: handleCanCollectByCouponId

---

src/screens/coupons/ExpiredCouponScreen/index.tsx

- fix navigate on ExpiredCouponScreen
- Test A

fix: navigateTo causesscreen

---

src/components/atomics/animations/NewTicketAnimation/index.tsx

Revert "feat: native animated toast"

---

package.json
src/components/atomics/animations/NewTicketAnimation/index.tsx
src/components/atomics/buttons/CollectableButton/index.tsx
src/components/moleculars/NewHeader/TicketSection/index.tsx
src/config/navigation/index.tsx
src/config/testUtils/renders.tsx
src/contexts/clubSubscriptionContext/index.tsx
src/lib/formatters/dateFormatter/index.ts
src/screens/content/EarnTicketsScreen/TicketsSection/ClubDailyTicketCard/index.tsx
src/screens/content/EarnTicketsScreen/TicketsSection/ClubMonthlyTicketCard/index.tsx
src/utils/translations/en.json
src/utils/translations/pt.json
yarn.lock

- Animation with 2 seconds
- Animation on club cards
https://github.com/RibonDAO/app/assets/110051338/99171cb3-00bd-4919-8ac9-c5a7e7c699c1
https://github.com/RibonDAO/app/assets/110051338/7aaf9551-4945-44c0-9a66-58269c8735c9
- Test A

feat: adjusts from last release

---

app.config.js

- app new version & new build
- Test A

feat: app new version

---

app.config.js
src/contexts/clubSubscriptionContext/index.tsx

- club subscription context(safe operator)
- Test A

fix: club subscription context

---

app.config.js

Remove ipad support.
`app.config.js->ios->supportsTablet` is a shorthand for `info.plist->UISupportedInterfaceOrientations~ipad`
https://docs.expo.dev/versions/latest/config/app/#supportstablet

feat: drop ipad support 😃😃😃

---

app.config.js

Revert "feat: drop ipad support "

---

src/screens/content/EarnTicketsScreen/Header/index.tsx
src/screens/content/EarnTicketsScreen/TabViewSection/index.tsx
src/screens/content/EarnTicketsScreen/TabViewSection/styles.ts
src/screens/content/EarnTicketsScreen/index.tsx
src/utils/translations/en.json
src/utils/translations/pt.json

- earn tickets header with scroll
- Test A

Fix: earn tickets header with scroll

---

src/screens/donations/CausesScreen/index.tsx

- Fix causes screen merge
- Test A

fix: use flatlist in causes screen

---

src/components/moleculars/Accordion/index.test.tsx
src/components/moleculars/Accordion/index.tsx
src/components/moleculars/Accordion/styles.ts
src/components/moleculars/AccordionList/index.tsx
src/components/moleculars/AccordionList/styles.ts

- Creates the accordion list 
put it in any place with a list of items:
```js
<AccordionList
title="Por projeto"
impactList={[
{
title: "Item 1",
subtitle: "Subtitle 1",
iconUrl: "https://picsum.photos/200",
description: "This is the description for item 1.",
},
{
title: "Item 2",
subtitle: "Subtitle 2",
iconUrl: "https://picsum.photos/200",
description: "This is the description for item 2.",
},
{
title: "Item 3",
subtitle: "Subtitle 3",
iconUrl: "https://picsum.photos/200",
description: "", // No description for this item
},
{
title: "Item 4",
subtitle: "Subtitle 4",
iconUrl: "https://picsum.photos/200",
description: "This is the description for item 4.",
},
]}
/>
```

feat: accordion list

---

src/screens/promoters/SubscriptionsScreen/index.tsx

fix: subscription pix card

---

src/screens/donations/CausesScreen/ReportsSection/index.tsx

- Added safe operator
- Test A

fix: report without name

---

app.config.js
src/screens/donations/CausesScreen/Header/index.tsx
src/screens/donations/CausesScreen/index.tsx
src/screens/donations/HomeScreen/index.tsx

- adjust redirect when has external id

fix: adjust redirect when has external id

---

src/contexts/ticketsContext/index.tsx

fix: update tickets counter params use effect

---

src/components/moleculars/layouts/PrivacyPolicyLayout/index.tsx
src/components/moleculars/layouts/PrivacyPolicyLayout/styles.ts
src/hooks/useFormattedImpactText/index.tsx
src/screens/donations/auth/DonationSignInScreen/index.tsx
src/screens/donations/auth/DonationSignInScreen/styles.ts
src/utils/translations/en.json
src/utils/translations/pt.json

-  copy and color adjust on PrivacyPolicyLayout and DonationSignInScreen 
- Test A

prod 657: copy and color adjust

---

src/screens/donations/auth/DonationInProgressSection/index.tsx

- animation start frame
- Test A

fix: animation start frame

---

src/contexts/clubSubscriptionContext/index.tsx
src/lib/formatters/dateFormatter/index.ts
src/screens/content/EarnTicketsScreen/TicketsSection/ClubMonthlyTicketCard/index.tsx
src/screens/promoters/SubscriptionsScreen/index.tsx
src/utils/translations/en.json
src/utils/translations/pt.json

- Fix benefits desappear when cancel subscription
- Shows cancel subscriptions
- eg: closes [#PROD3-649]()
- Test subscriptions club from pix and card
- Test cancel subscription

fix: benefits disappear when cancel subscription

---

src/hooks/useTickets/index.ts
src/screens/content/EarnTicketsScreen/TicketsSection/DailyTicketCard/index.tsx

- handleCollectDailyTicket from Ribon integration
- Test A

fix: handleCollectDailyTicket from Ribon integration

---

src/components/moleculars/ConfigItem/index.tsx
src/components/moleculars/ConfigItem/styles.ts
src/components/moleculars/HeaderTemplate/index.tsx
src/components/moleculars/HeaderTemplate/styles.ts

- Increase press area for menu icon
- [#prod3-668](https://ribon.atlassian.net/browse/PROD3-668)

fix: increase press area on menu icon

---

src/components/moleculars/SliderButton/index.tsx
src/screens/donations/SelectTicketsScreen/Lottie3Steps/index.tsx

- fix minimumValue and steps
- Do the test with 7 tickets and nonprofit with 3 tickets minimum

fix: lottie 3 steps

---

src/components/moleculars/SliderButton/index.tsx
src/screens/donations/SelectTicketsScreen/Lottie3Steps/index.tsx
src/screens/donations/SelectTicketsScreen/styles.ts

- layout & minimumValue
- Test A

fix: layout & minimumValue

---

src/screens/donations/SelectTicketsScreen/styles.ts

- textContainer Height to support dynamic text
- Test A

Fix: release 6 0 1 textContainer Height to support dynamic text

---

src/screens/donations/DonationDoneStack/PostDonationScreen/index.tsx

- adjust the donation screen background position to remove the bottom and side margin

fix: post donation background position

---

app.config.js
src/screens/donations/SelectTicketsScreen/index.tsx
src/screens/donations/SelectTicketsScreen/styles.ts
src/screens/donations/auth/DonationInProgressSection/index.tsx

- adjust the donation in progress animation duration to 5.5 seconds
- fix the back button on the select tickets screen
- updates app version

fix: adjust animation and back button

---

src/screens/auth/SignInScreen/index.tsx
src/screens/donations/CausesScreen/CausesSection/NonProfitsList/NonProfitCarousel/index.tsx
src/screens/donations/CausesScreen/CausesSection/NonProfitsList/index.test.tsx
src/screens/donations/CausesScreen/CausesSection/NonProfitsList/index.tsx
src/screens/donations/CausesScreen/CausesSection/index.tsx
src/screens/donations/CausesScreen/UnauthorizedModal/index.tsx
src/screens/donations/CausesScreen/index.tsx
src/utils/translations/en.json
src/utils/translations/pt.json

- blocks direct donation for non authenticated users
- closes [PROD3-718](https://ribon.atlassian.net/browse/PROD3-718)
- [ X] New feature (non-breaking change which adds functionality)

feat: prod3-718

---

app.config.js
src/config/navigation/LinkingConfiguration.ts

fix: magic link redirect

---

src/components/moleculars/Accordion/AccordionPlaceholder/index.tsx
src/components/moleculars/Accordion/index.test.tsx
src/components/moleculars/Accordion/index.tsx
src/components/moleculars/Accordion/styles.ts

- Fix accordion behavior to minimize when changes the screen 
- Fix the ticket icon to don't be clickable 
- no

fix: accordion behavior

---

App.tsx
app.config.js
package.json
yarn.lock

- We are facing a small number of crashes due to expo-updates, which has not been used

fix: remove expo-updates

---

src/utils/translations/en.json
src/utils/translations/pt.json

- Add new copy to onboarding page
- eg: closes [#PROD3-680](https://ribon.atlassian.net/jira/software/c/projects/PROD3/boards/28?selectedIssue=PROD3-680)
- Verify the new copy onboarding page and about tickets on causes screen in on "?" icon

[PROD3-680] Add new copy to onboarding page

---

app.config.js
src/screens/users/ImpactScreen/ProfileSection/index.tsx

- Fix background color and updates app version
- Test A

fix: statistic cards

---

src/utils/translations/en.json
src/utils/translations/pt.json

Revert "[PROD3-680] Add new copy to onboarding page"

---

src/screens/promoters/SubscriptionsScreen/index.tsx

- Filters out business subscriptions from subscriptions page
- [#prod3-659](https://ribon.atlassian.net/browse/PROD3-659)
- Go to subscriptions page logged in as a user that has business subscriptions

feat: filters business subscr. out of subsc. page

---

package.json
src/screens/donations/DonationDoneStack/DonationDoneScreen/getRandomImages.ts
src/screens/donations/DonationDoneStack/DonationDoneScreen/index.tsx
src/screens/donations/DonationDoneStack/DonationDoneScreen/styles.ts
src/utils/translations/en.json
src/utils/translations/pt.json
yarn.lock

Adds the donation count to the donation done screen
Make an donation and check if the count appears. It will not show up if the checkbox do.

Adds donation count to post donation

---

src/utils/translations/en.json
src/utils/translations/pt.json

Fix toast messages in the sign-in flow

fix: login messages

---

src/components/moleculars/SliderButton/index.tsx
src/screens/donations/SelectTicketsScreen/Lottie3Steps/index.tsx
src/screens/donations/SelectTicketsScreen/Lottie3Steps/styles.ts

Percent-based animation using reanimated and react component rendering.
https://github.com/user-attachments/assets/e8ba6c53-6630-41b6-88af-914f499b5694

feat: percentage-based animation, using reanimated for transitions
